//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaLINK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public int customer_id { get; set; }
        public int category_id { get; set; }
        public string booking_date { get; set; }
        public decimal total_price { get; set; }
        public int status { get; set; }
    
        public virtual Service_Category Service_Category { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
