//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaLINK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Provider
    {
        public int provider_id { get; set; }
        public int user_id { get; set; }
        public int category_id { get; set; }
        public string location { get; set; }
        public string rating { get; set; }
        public string availability { get; set; }
    
        public virtual Service_Category Service_Category { get; set; }
    }
}
