//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaLINK
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual User_Account User_Account { get; set; }
        public virtual User_Category User_Category { get; set; }
        public virtual UserRole UserRole1 { get; set; }
        public virtual UserRole UserRole2 { get; set; }
    }
}
