//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaLINK
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int id { get; set; }
        public string userId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> storeId { get; set; }
        public Nullable<int> managerId { get; set; }
    }
}
